### ISSUE TITLE
Failed to fetch dynamically imported module - datatable

### ISSUE THREAD

**Issue by JakubEleniuk** [lukethacoder/lwc-garden#3]
Firstly thank you for creating this very promising project!

I encountered a problem with loading base datatable component in my own LWC, as such I tried to test this component in the provided example https://lwc.garden/examples/lightning-base-components/

The datatable works in the stackblitz environment but unfortunately after downloading the example and doing npm install I encountered the problem again.

Here is a video of me trying different components and failing on the datatable:

https://github.com/lukethacoder/lwc-garden/assets/92299434/0b841bca-fb77-4eb6-a568-ffb24d1eac9a

![image](https://github.com/lukethacoder/lwc-garden/assets/92299434/930c2237-d090-48d4-ace5-de3d40b350c7)

Could this be a problem with the environment?

Node v18.18.2
Windows
Chrome

**Comment by lukethacoder** [comment]
Had a look into this. Quite odd that this works fine in StackBlitz but not locally.

Only variable I can see is that we're both using Windows on our local machines vs StackBlitz runing some flavour of linux.

Created a small repro of declaratively rendering the `lightning-datatable`. Which again, runs fine in StackBlitz, but as soon as I pull to my local machine and try to get it running, throws the same errors you have run into.

https://stackblitz.com/edit/lightning-base-components-playground?file=modules%2Fexample%2Fapp%2Fapp.html

I wonder what magic Salesforce are doing in `lightning-datatable` that makes it only work (presumably) only on Unix based machines?

---

https://www.npmjs.com/package/lightning-base-components?activeTab=code

Poking at the source code, it looks like `lightning-datatable` is quite chunky, so not too sure where to even start pulling this apart. Even if I did find something, not too much we can do as the npm package is no longer open-sourced ([it used to be, sort of](https://github.com/salesforce/base-components-recipes)) and does not have a repo to raise bugs in. Unless this is some underlying LWR issue?

![image](https://github.com/lukethacoder/lwc-garden/assets/13529535/f4f2e2a4-50ba-49ff-b530-5e7689e34bd6)

**Comment by JakubEleniuk** [comment]
Yop it looks like a windows specific issue.
See https://github.com/salesforce/lwc/issues/2993 and https://github.com/salesforce/lwc/issues/2981

The total list of broken components from my testing:

datatable
formattedAddress
formattedDateTime
formattedName
formattedNumber
formattedTime
input
inputAddress
inputLocation
inputName
progressBar
progressIndicator
progressStep
relativeDateTime
treeGrid

Will try to fiddle with WSL when I have time.

**Comment by JakubEleniuk** [comment]
I roughly followed the steps mentioned here [lwr demo windows steps](https://github.com/rahulgawale/lwr-demo?tab=readme-ov-file#windows) and can confirm that everything seems to work through WSL, altough I did not copy the project so the performance was miserable (see [slow wsl](https://stackoverflow.com/questions/68972448/why-is-wsl-extremely-slow-when-compared-with-native-windows-npm-yarn-processing))

I would suggest leaving this issue open until a Windows setup guideline is created.
I might contribute if it doesn't exist by the time I come back to work with LWCs in the coming weeks.

**Comment by lukethacoder** [comment]
left a comment on https://github.com/salesforce/lwc/issues/2993 around the issue. I have a feeling it might be related to the way the `lightning-base-components` are split into sub folders. From a vanilla JS POV there are no issues, but the way LWR resolves these causes issues on windows.

Given LWR hasnt changed a heap in the past few years, and they've said they don't officially support windows (wild), I don't see either the `@lwrjs/*` packages being fixed OR `lightning-base-components` being fixed.

I'd really rather not have to poke around with WSL. Like you've seen, it is slow and not everyone on a windows machine has access to WSL (see most big companies that lock down their machines). 

I'm currently looking into the root cause of the `@lwrjs/*` package bugs and seeing if they're simple enough to fix. Hoping that getting them working properly on windows would fix this. Worst case, a "windows" fork of `lightning-base-components` should do the trick too.

**Comment by lukethacoder** [comment]
@JakubEleniuk have been poking around in `@lwrjs/*` package sources and managed to get native windows support working. Here's the snippet from the updated documentation. Let me know if you're still having issues on windows.

## Windows Support for `lightning-base-components`

By default, Salesforce does not offer proper Windows support due to bugs in their `@lwrjs/*` packages.

We can add native windows support (no need for WSL) via [`@lukethacoder/lwrjs-module-registry`](https://www.npmjs.com/package/@lukethacoder/lwrjs-module-registry). This package is an opinionated edit that fixes Windows specific issues as well as a few other bugs.

```cmd
pnpm add @lukethacoder/lwrjs-module-registry
```

### Configuration

In your `package.json`, add the following override.

```json
{
  "pnpm": {
    "overrides": {
      "@lwrjs/module-registry": "npm:@lukethacoder/lwrjs-module-registry"
    }
  }
}
```
> NOTE: this is for pnpm. NPM and Yarn have a similar overrides method.

**Comment by rahulgawale** [comment]
@lukethacoder 

I have installed the `@lukethacoder/lwrjs-module-registry` package.

this is the snippet from the `package.json` file.
```
  "overrides": {
    "@lwc/module-resolver": "$@lukethacoder/lwc-module-resolver"
  }
```

Following is `lwr.config.js`.

```
{
	"lwc": {
		"modules": [
			{
				"dir": "/src/modules/app",
				"namespace": "app"
			},
			{
				"dir": "/src/modules/ui",
				"namespace": "ui"
			},
			{
				"name": "contexts",
				"path": "/src/contexts/contexts.js"
			}
		]
	},
	"routes": [
		{
			"id": "app",
			"path": "/",
			"rootComponent": "app/root",
			"layoutTemplate": "$layoutsDir/app.html",
			"bootstrap": {
				"syntheticShadow": true
			}
		},
		{
			"id": "auth-callback",
			"path": "/auth-callback",
			"rootComponent": "ui/card",
			"layoutTemplate": "$layoutsDir/auth-callback.html"
		}
	],
	"bundleConfig": {
		"exclude": [
			"lwc"
		]
	},
	"assets": [
		{
			"alias": "jsforceDir",
			"dir": "$rootDir/src/jsforce",
			"urlPath": "/jsforce"
		},
		{
			"dir": "$rootDir/src/assets/fonts",
			"urlPath": "/fonts"
		},
		{
			"file": "$rootDir/src/assets/utilitySprite.svg",
			"urlPath": "/lightning.utilitySprite"
		},
		{
			"alias": "assetsDir",
			"dir": "$rootDir/src/assets",
			"urlPath": "/assets"
		}
	]
}
```

When I ran `npm run dev` it gave me this error on windows.

```
PS D:\KTL Projects\crudspace> npm run dev

> crudspace@0.0.1 dev
> lwr dev

node:internal/modules/esm/resolve:853
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@lwrjs/config' imported from D:\KTL Projects\crudspace\node_modules\@lwrjs\module-registry\build\es\signature.js
    at packageResolve (node:internal/modules/esm/resolve:853:9)
    at moduleResolve (node:internal/modules/esm/resolve:910:20)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v20.11.0
```
Am I missing anything?
