### ISSUE TITLE
Why did you need to create separate module loaders?

### ISSUE THREAD

**Issue by banderson-stripe** [lukethacoder/lwc-garden#4]
In your `package.json` I see these two declarations:

```
"@lukethacoder/lwc-module-resolver": "^6.5.0",
"@lukethacoder/lwrjs-lwc-module-provider": "^0.12.2"
```

I'm curious why you had to create these two. I thought LWR does these two functions already?

**Comment by lukethacoder** [comment]
Yes, Salesforce does provide their own modules for these, [`@lwc/module-resolver`](https://github.com/salesforce/lwc/blob/master/packages/%40lwc/module-resolver/README.md) and [`@lwrjs/lwc-module-provider
`](https://www.npmjs.com/package/@lwrjs/lwc-module-provider).

The reason for the custom packages is to add (in my opinion) much needed resolver functionality when working with the on-platform folder structure.

The open source version of LWC requires a specific [folder structure](https://lwc.dev/guide/reference#modules), and assumes namespaces based on said folder structure.

e.g this folder structure using open source LWC would assume your namespaces are `one` and `two`. You would access each LWC via `<one-button/>` and `<two-button/>`.

```
.
├── one/
│   └── button/
│       ├── button.html
│       └── button.js
└── two/
    └── button/
        ├── button.html
        └── button.js
```

This is different to what a typical on-platform folder structure is.

```
.
└── force-app/
    ├── main/
    │   └── default/
    │       └── lwc/
    │           └── button/
    │               ├── button.html
    │               ├── button.js
    │               └── button.js-meta.xml
    └── utilities/
        └── default/
            └── lwc/
                └── utilities/
                    ├── utilities.js
                    └── utilities.js-meta.xml
```

---

The custom modules allow for two things:
1. Namespacing a directory (instead of it being inferred from the folder structure)
2. Multi-directory namespaced component (the above salesforce example would access both folders via the `c` namespace to align with how they would function on-platform)

The custom modules are merely extensions on salesforces modules. You can use them as if they were the standard modules if you don't need the on-platform specific edits.

The README.md ([`@lukethacoder/lwc-module-resolver`](https://github.com/lukethacoder/lwc-module-resolver) & [`@lukethacoder/lwrjs-lwc-module-provider`](https://github.com/lukethacoder/lwrjs-lwc-module-provider)) for each custom module go into a bit more depth.

**Comment by banderson-stripe** [comment]
Perfect thank you for explaining this
